# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f76b7f40-618a-4861-91c0-53aef3a56eb5";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f76b7f40-618a-4861-91c0-53aef3a56eb5";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/f76b7f40-618a-4861-91c0-53aef3a56eb5";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f76b7f40-618a-4861-91c0-53aef3a56eb5";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/f76b7f40-618a-4861-91c0-53aef3a56eb5";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/var/lib/libvirt" =
    { device = "/dev/disk/by-uuid/f76b7f40-618a-4861-91c0-53aef3a56eb5";
      fsType = "btrfs";
      options = [ "subvol=@libvirt" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FA1B-5231";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
